
name: Continuous integration Development

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - 'development**'
      - 'chat**'
      - 'friends**' 
      - 'analytics**'
      - 'testing**'
  pull_request:
    branches:
      - 'development**'
      - 'chat**'
      - 'friends**'
      - 'analytics**'
      - 'testing'
      

jobs:

  build:
    defaults:
      run:
        working-directory: Capstone MeetApp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: 
          node-version: 18
      - run: npm install --legacy-peer-deps
      - name: maps api environment
        run: touch libs/app/map/feature/src/lib/maps/environment.ts | printf "export const environment={API_KEY:'${{secrets.MAPS_API_KEY}}'};" > libs/app/map/feature/src/lib/maps/environment.ts
      - name: backend setup
        run: touch libs/services/src/lib/environment.ts | printf  "export const environment={BASE_URL:'${{secrets.API_BASE_URI}}',BACKEND_API_KEY:'${{secrets.MEETAPP_API_KEY}}'};" > libs/services/src/lib/environment.ts
      - name: env file
        run: touch .env | printf "DB_CONNECTION_STRING_SEDI='${{secrets.DB_CONNECTION_STRING_SEDI}}'\nDB_NAME_SEDI='${{secrets.DB_NAME_SEDI}}'\nJWT_PRIVATE_KEY='${{secrets.JWT_PRIVATE_KEY}}'\nMEETAPP_API_KEY='${{secrets.MEETAPP_API_KEY}}'"> .env
      - run: npm run build

  test:
    defaults:
      run:
        working-directory: Capstone MeetApp 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: 
          node-version: 18
      - run: npm install --legacy-peer-deps
      - name: maps api environment
        run: touch libs/app/map/feature/src/lib/maps/environment.ts | printf "export const environment={API_KEY:'${MAPS_API}'};" > libs/app/map/feature/src/lib/maps/environment.ts
      - name: backend setup
        run: touch libs/services/src/lib/environment.ts | printf  "export const environment={BASE_URL:'${API_BASE_URI}',BACKEND_API_KEY:'${API_KEY}'};" > libs/services/src/lib/environment.ts
      - run: npm run test
      - name: print out codeCov secret
        run: printf "${{secrets.CODECOV_TOKEN}}"
      - name: Coverage Report
        uses: codecov/codecov-action@v3
        env: 
            CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
            files: coverage/lcov.info
  
  lint:
    defaults:
      run:
        working-directory: Capstone MeetApp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: 
          node-version: 18
      - run: npm install --legacy-peer-deps
      - run: npm run lint

  api: 
    defaults:
      run:
        working-directory: Capstone MeetApp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: 
          node-version: 18
      - run: npm install --legacy-peer-deps
      - name: Start API Server
        run: npm run serve:api:dev

  e2e:
    defaults:
      run:
        working-directory: Capstone MeetApp\
    needs: api
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: 
          node-version: 18
      - run: npm install --legacy-peer-deps
      - name: maps api environment
        run: touch libs/app/map/feature/src/lib/maps/environment.ts | printf "export const environment={API_KEY:'${MAPS_API}'};" > libs/app/map/feature/src/lib/maps/environment.ts
      - name: backend setup
        run: touch libs/services/src/lib/environment.ts | printf  "export const environment={BASE_URL:'${API_BASE_URI}',BACKEND_API_KEY:'${API_KEY}'};" > libs/services/src/lib/environment.ts 
      - name: Wait for API to Start
        run: |
          # Wait for the API to start (adjust the sleep duration as needed)
          sleep 10
      - name: run end-to-end tests
        run: npm run e2e
      - name: Non-Functional indicatorss
        run: npm run lighthouse-audit
      - name: change directory
        run: cd tools 
      - name: script for extracting indicators from report
        run: node ./tools/lighthouse.config
      
 

    
