
name: Continuous integration Development

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - 'development**'
      - 'ui**'
      - 'auth**'
      - 'map**'
      - 'profile**'
      - 'home**'
      - 'organiser**'
      - 'settings**'
      - 'events**'
      - 'friends**' 
      - 'analytics**'
  pull_request:
    branches:
      - 'development**'
      - 'ui**'
      - 'auth**'
      - 'map**'
      - 'profile**'
      - 'home**'
      - 'organiser**'
      - 'settings**'
      - 'events**'
      - 'friends**'
      - 'analytics**'
      

jobs:

  build:
    defaults:
      run:
        working-directory: Capstone MeetApp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: 
          node-version: 18
      - run: npm install --legacy-peer-deps
      - name: maps api environment
        run: touch libs/app/map/feature/src/lib/maps/environment.ts | printf "export const environment={API_KEY:'${{secrets.MAPS_API_KEY}}'};" > libs/app/map/feature/src/lib/maps/environment.ts
      - name: backend setup
        run: touch libs/services/src/lib/environment.ts | printf  "export const environment={BASE_URL:'${{secrets.API_BASE_URI}}',BACKEND_API_KEY:'${{secrets.MEETAPP_API_KEY}}'};" > libs/services/src/lib/environment.ts
      - name: env file
        run: touch .env | printf "DB_CONNECTION_STRING_SEDI='${{secrets.DB_CONNECTION_STRING_SEDI}}'\nDB_NAME_SEDI='${{secrets.DB_NAME_SEDI}}'\nJWT_PRIVATE_KEY='${{secrets.JWT_PRIVATE_KEY}}'\nMEETAPP_API_KEY='${{secrets.MEETAPP_API_KEY}}'"> .env
      - run: npm run build

  test:
    defaults:
      run:
        working-directory: Capstone MeetApp 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: 
          node-version: 18
      - run: npm install --legacy-peer-deps
      - name: maps api environment
        run: touch libs/app/map/feature/src/lib/maps/environment.ts | printf "export const environment={API_KEY:'${MAPS_API}'};" > libs/app/map/feature/src/lib/maps/environment.ts
      - name: backend setup
        run: touch libs/services/src/lib/environment.ts | printf  "export const environment={BASE_URL:'${API_BASE_URI}',BACKEND_API_KEY:'${API_KEY}'};" > libs/services/src/lib/environment.ts
      - run: npm run test
      - name: print out codeCov secret
        run: printf "${{secrets.CODECOV_TOKEN}}"
      - name: Coverage Report
        uses: codecov/codecov-action@v3
        env: 
            CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
            files: coverage/lcov.info
  
  lint:
    defaults:
      run:
        working-directory: Capstone MeetApp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: 
          node-version: 18
      - run: npm install --legacy-peer-deps
      - run: npm run lint

  e2e:
    defaults:
      run:
        working-directory: Capstone MeetApp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: 
          node-version: 18
      - run: npm install --legacy-peer-deps
      - name: maps api environment
        run: touch libs/app/map/feature/src/lib/maps/environment.ts | printf "export const environment={API_KEY:'${MAPS_API}'};" > libs/app/map/feature/src/lib/maps/environment.ts
      - name: backend setup
        run: touch libs/services/src/lib/environment.ts | printf  "export const environment={BASE_URL:'${API_BASE_URI}',BACKEND_API_KEY:'${API_KEY}'};" > libs/services/src/lib/environment.ts
      - run: npm run e2e
 

    
