name: CI
on:
  workflow_dispatch:
  
  push:
    branches:
      - auth
      - development
      
  pull_request:
    branches:
      - auth
      - development

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
      - name: nodeJS
        uses: actions/setup-node@v3
      - run: npm ci
      - run: npm install
      - run: npx nx format:check
      - run: npx nx run-many --target=lint 
      - run: npx nx run-many --target=test to run all tests
      - run: npx nx run-many --target=build 
     
 
    
