name: Continuous_integration
on:
  workflow_dispatch:
  
  push:
    branches:
      - auth
      - development
      - main
      
  pull_request:
    branches:
      - auth
      - development

jobs:
  build:
    defaults:
      run:
        working-directory: Capstone MeetApp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: 
          node-version: 18
      - run: npm ci
      - run: npm run build

  test:
    defaults:
      run:
        working-directory: Capstone MeetApp 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: 
          node-version: 18
      - run: npm ci
      - run: npm run test
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3 
        with:
          token: ${{ secrets.CODECOV_TOKEN}}
  
  lint:
    defaults:
      run:
        working-directory: Capstone MeetApp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: 
          node-version: 18
      - run: npm ci
      - run: npm run lint

  e2e:
    defaults:
      run:
        working-directory: Capstone MeetApp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: 
          node-version: 18
      - run: npm ci
      - run: npm run e2e
 
 
    
