
name: Continuous integration Development

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - 'development**'
      - 'ui**'
      - 'auth**'
      - 'map**'
      - 'profile**'
      - 'home**'
      - 'organiser**'
      - 'settings**'
      - 'events**'
      
  pull_request:
    branches:
      - 'development**'
      - 'ui**'
      - 'auth**'
      - 'map**'
      - 'profile**'
      - 'home**'
      - 'organiser**'
      - 'settings**'
      - 'events**'
      

jobs:

  build:
    defaults:
      run:
        working-directory: Capstone MeetApp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: 
          node-version: 18
      - run: npm install --legacy-peer-deps
      - run: npm run build

  test:
    defaults:
      run:
        working-directory: Capstone MeetApp 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: 
          node-version: 18
      - run: npm install --legacy-peer-deps
      - run: npm run test
      - name: print out codeCov secret
        run: printf "${{secrets.CODECOV_TOKEN}}"
      - name: Coverage Report
        uses: codecov/codecov-action@v3
        env: 
            CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
            files: coverage/lcov.info
  
  lint:
    defaults:
      run:
        working-directory: Capstone MeetApp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: 
          node-version: 18
      - run: npm install --legacy-peer-deps
      - run: npm run lint

  e2e:
    defaults:
      run:
        working-directory: Capstone MeetApp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: 
          node-version: 18
      - run: npm install --legacy-peer-deps
      - run: npm run e2e
 

    
