
name: Continuous integration Development

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - 'testing**'
  pull_request:
    branches:
      - 'testong**'
      

jobs:
    e2e:
        defaults:
          run:
            working-directory: Capstone MeetApp
        runs-on:  windows-latest
        steps:
          - uses: actions/checkout@v3
          - uses: actions/setup-node@v3
            with: 
              node-version: 18
          - run: npm install --legacy-peer-deps
          - name: lighthouse 
            run: npm run lighthouse-audit
          - name: change directory
            run: cd tools 
            shell: bash
          - name: script for extracting indicators from report
            run: node ./tools/lighthouse.config
          - name: maps api environment
            run: touch libs/app/map/feature/src/lib/maps/environment.ts | printf "export const environment={API_KEY:'${MAPS_API}'};" > libs/app/map/feature/src/lib/maps/environment.ts
            shell: bash
          - name: backend setup
            run: touch libs/services/src/lib/environment.ts | printf  "export const environment={BASE_URL:'${API_BASE_URI}',BACKEND_API_KEY:'${API_KEY}'};" > libs/services/src/lib/environment.ts
            shell: bash
          - run: npm run e2e